import './assets/icon/icon-512x512.svg';
import './assets/icon/icon-192x192.svg';
import './assets/icon/icon-144x144.png';
import './manifest.json'
import './assets/*.jpg'
import './style/*.css'
import './pages/*.html'
import './nav.html'
import './team.html'
import './script/nav.js'
import './script/idb.js'
import './script/db.js'
import './script/api.js'
import './script/script.js'
import './script/sw-register.js'
